In [2]:
                      ####################Boolean Indexing####################

In [2]:
import numpy as np
arr=np.random.randn(7,4)
print(arr)
names=['Aman','Agarwal','Aman','Ankit','Akshay','Aman','Agarwa']
name=np.array(names)

[[-0.54331017  1.67309898 -0.94641707  0.74606734]
 [-0.78335108  0.15751985 -0.62211848  0.20308578]
 [-0.2172107   0.98706595 -0.98184055 -1.17013036]
 [-1.5266321  -0.85336676 -0.23269859  0.15248429]
 [ 0.91951417 -1.33206009 -1.39373123 -1.085376  ]
 [ 0.16772139  0.27234865  1.37606751  0.73531726]
 [-1.92364311 -0.30682941 -0.75498053  1.10168771]]


In [3]:
name=='Aman' #The numpy array will make comparision with each entry

array([ True, False,  True, False, False,  True, False], dtype=bool)

In [4]:
print(arr[name=='Aman']) #it will select those entries for which name=='Aman' is true

[[-0.54331017  1.67309898 -0.94641707  0.74606734]
 [-0.2172107   0.98706595 -0.98184055 -1.17013036]
 [ 0.16772139  0.27234865  1.37606751  0.73531726]]


In [5]:
print(arr[name=='Aman',2:])#indexing the columns

[[-0.94641707  0.74606734]
 [-0.98184055 -1.17013036]
 [ 1.37606751  0.73531726]]


In [6]:
#Now name should not be equal to Aman except this anyname can be present for this we can do it like this

In [7]:
print(arr[name!='Aman',2:])#1st method

[[-0.62211848  0.20308578]
 [-0.23269859  0.15248429]
 [-1.39373123 -1.085376  ]
 [-0.75498053  1.10168771]]


In [8]:
print(arr[~(name=='Aman'),2:])#by using tilde operator

[[-0.62211848  0.20308578]
 [-0.23269859  0.15248429]
 [-1.39373123 -1.085376  ]
 [-0.75498053  1.10168771]]


In [9]:
#we can use & or | opeartor also to combine the two conditions for this we can fo it in this way

In [10]:
print(arr[(name=='Aman')|(name=='Agarwal')])#either of the condition can be true

[[-0.54331017  1.67309898 -0.94641707  0.74606734]
 [-0.78335108  0.15751985 -0.62211848  0.20308578]
 [-0.2172107   0.98706595 -0.98184055 -1.17013036]
 [ 0.16772139  0.27234865  1.37606751  0.73531726]]


In [11]:
print(arr[(name=='Aman')&(name=='Agarwal')])

[]


In [12]:
arr[arr<0]=0
print(arr)

[[ 0.          1.67309898  0.          0.74606734]
 [ 0.          0.15751985  0.          0.20308578]
 [ 0.          0.98706595  0.          0.        ]
 [ 0.          0.          0.          0.15248429]
 [ 0.91951417  0.          0.          0.        ]
 [ 0.16772139  0.27234865  1.37606751  0.73531726]
 [ 0.          0.          0.          1.10168771]]


In [13]:
arr[name!='Aman']=0

In [14]:
print(arr)

[[ 0.          1.67309898  0.          0.74606734]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.98706595  0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.16772139  0.27234865  1.37606751  0.73531726]
 [ 0.          0.          0.          0.        ]]


In [15]:
                      ####################Fancy Indexing####################

In [16]:
arr=np.arange(40).reshape(8,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [17]:
arr[[4,3,0,1,6]] #firstly 4th one will be select then after this 3rd one then 0th one then 1st one then 6th one will be select

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34]])

In [18]:
arr[[-4,-3,0,-1,-6]] #-ve sign indicate from the last because from last indexing is form -1 #it is selecting the one dimensional array corresponding to the each index

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4],
       [35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14]])

In [19]:
arr[[-1,-3,0,-1,-6],[4,2,1,3,2]] #it will result the one dimensional array it will create the tuple like (-1,4),(-3,2) and so on

array([39, 27,  1, 38, 12])

In [20]:
#Now by applying it we can also get 2d array like this we can apply these functions
arr[[-1,-3,0,-1,-6]][:,[4,2,1,3,2]] #it will make the tuples like (-1,4),(-1,2),(-1,1),(-1,3),(-1,2) and so on...

array([[39, 37, 36, 38, 37],
       [29, 27, 26, 28, 27],
       [ 4,  2,  1,  3,  2],
       [39, 37, 36, 38, 37],
       [14, 12, 11, 13, 12]])

In [21]:
arr[[-1,-3,0,-1,-6],:2] #slicing the number of rows only publishing the rows from 0 to 1.

array([[35, 36],
       [25, 26],
       [ 0,  1],
       [35, 36],
       [10, 11]])

In [22]:
                ####################Transposing Arrays and Swapping Axes#####################

In [23]:
x=arr.T #it will provide the transpose of the Array it will be a copy 
x[0][0]=97
print(x)

[[97  5 10 15 20 25 30 35]
 [ 1  6 11 16 21 26 31 36]
 [ 2  7 12 17 22 27 32 37]
 [ 3  8 13 18 23 28 33 38]
 [ 4  9 14 19 24 29 34 39]]


In [24]:
print(arr) #if we change the elements in the transpose those changes will reflect into the orginial array 

[[97  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [25]:
arr1= np.arange(16).reshape((2, 2, 4)) #the dimension is depending how many argumnents we are passing in the reashape function
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [26]:
#.transpose() function 
arr1.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [27]:
arr1.transpose((0,1,2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [28]:
arr1.transpose(2,1,0)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [29]:
y = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

In [30]:
np.swapaxes(y,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [31]:
np.swapaxes(y,1,2)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [32]:
arr1.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [33]:
arr1.swapaxes(0,2)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [34]:
           ######################Universal Functions: Fast Element-Wise Array Functions########################

In [35]:
z=np.array([1,2,3,4,59,10])
m=np.sqrt(z)
print(m)

[ 1.          1.41421356  1.73205081  2.          7.68114575  3.16227766]


In [36]:
j=np.exp(z)
print(j)

[  2.71828183e+00   7.38905610e+00   2.00855369e+01   5.45981500e+01
   4.20121040e+25   2.20264658e+04]


In [37]:
#providing the absolute value of each element
print(np.abs(z))

[ 1  2  3  4 59 10]


In [38]:
#provding the square of the each element
print(np.square(z))

[   1    4    9   16 3481  100]


In [39]:
print(np.log(z))

[ 0.          0.69314718  1.09861229  1.38629436  4.07753744  2.30258509]


In [40]:
print(np.log10(z))

[ 0.          0.30103     0.47712125  0.60205999  1.77085201  1.        ]


In [41]:
print(np.log2(z))

[ 0.          1.          1.5849625   2.          5.88264305  3.32192809]


In [42]:
print(np.log1p(z))

[ 0.69314718  1.09861229  1.38629436  1.60943791  4.09434456  2.39789527]


In [43]:
#1 is representing +ve sign -1 is representing negative sign
b=[-1,-2,3,4,5]
print(np.sign(b))

[-1 -1  1  1  1]


In [44]:
n=[-1.2,-2.2,3.1,4.4,5.5]
print(np.ceil(n))

[-1. -2.  4.  5.  6.]


In [45]:
print(np.floor(n))

[-2. -3.  3.  4.  5.]


In [46]:
#round elements to the nearest integer
print(np.rint(n))
print(n)

[-1. -2.  3.  4.  6.]
[-1.2, -2.2, 3.1, 4.4, 5.5]


In [47]:
c,k=np.modf(n)
print(c)
print(k)

[-0.2 -0.2  0.1  0.4  0.5]
[-1. -2.  3.  4.  5.]


In [48]:
j=np.array([1,2,3])
print(np.isnan(j))

[False False False]


In [49]:
#check the elements they are finite or infinite
print(np.isfinite(n))

[ True  True  True  True  True]


In [50]:
#returning cosine value
print(np.cos(z))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362 -0.77108022 -0.83907153]


In [51]:
#returning hyperbolic values
print(np.cosh(z))

[  1.54308063e+00   3.76219569e+00   1.00676620e+01   2.73082328e+01
   2.10060520e+25   1.10132329e+04]


In [52]:
f = np.array([-1,1])
print(np.arccos(f))

[ 3.14159265  0.        ]


In [53]:
print(np.logical_not(z))

[False False False False False False]


In [54]:
lq=np.array([1.2,3.4,5.0,6.0,7.0])
pq=np.array([2.2,6.7,8.8,9.9,7.5])
print(np.add(lq,pq))

[  3.4  10.1  13.8  15.9  14.5]


In [55]:
print(np.subtract(lq,pq))

[-1.  -3.3 -3.8 -3.9 -0.5]


In [56]:
print(np.multiply(lq,pq))

[  2.64  22.78  44.    59.4   52.5 ]


In [57]:
#provide the actual value
print(np.divide(lq,pq))

[ 0.54545455  0.50746269  0.56818182  0.60606061  0.93333333]


In [58]:
#provides the floor value
print(np.floor_divide(lq,pq))

[ 0.  0.  0.  0.  0.]


In [59]:
print(np.power(lq,pq))

[  1.49347770e+00   3.63838577e+03   1.41558528e+06   5.05472321e+07
   2.17888997e+06]


In [60]:
lq=np.array([1.2,3.4,5.0,6.0,7.8])
print(np.maximum(lq,pq))

[ 2.2  6.7  8.8  9.9  7.8]


In [61]:
#ignores the NAN (Not a Number)
print(np.fmax(lq,pq))

[ 2.2  6.7  8.8  9.9  7.8]


In [62]:
print(np.minimum(lq,pq))

[ 1.2  3.4  5.   6.   7.5]


In [63]:
#providing the sign of other array to the another array
lqw=np.array([1,2,3,4,5])
lqe=np.array([-1,-3,-4,-9,-8])
print(np.copysign(lqw,lqe))

[-1. -2. -3. -4. -5.]


In [64]:
print(np.mod(lqw,lqe))

[ 0 -1 -1 -5 -3]


In [65]:
print(np.greater(lqw,lqe))

[ True  True  True  True  True]


In [66]:
print(np.greater_equal(lq,pq))

[False False False False  True]


In [67]:
print(np.equal(lq,pq))

[False False False False False]


In [68]:
print(np.not_equal(lq,pq))

[ True  True  True  True  True]


In [69]:
print(np.logical_or(lq,pq))

[ True  True  True  True  True]


In [70]:
print(np.logical_and(lq,pq))

[ True  True  True  True  True]


In [71]:
#logical xor  1 1 = 0 , 0 1 =1, 1 0 = 1, 0 0=1   
print(np.logical_xor(lq,pq))

[False False False False False]


In [72]:
            ##############################Array-Oriented Programming with Arrays#####################################

In [73]:
p=np.arange(5,20,0.1)
print(p)

[  5.    5.1   5.2   5.3   5.4   5.5   5.6   5.7   5.8   5.9   6.    6.1
   6.2   6.3   6.4   6.5   6.6   6.7   6.8   6.9   7.    7.1   7.2   7.3
   7.4   7.5   7.6   7.7   7.8   7.9   8.    8.1   8.2   8.3   8.4   8.5
   8.6   8.7   8.8   8.9   9.    9.1   9.2   9.3   9.4   9.5   9.6   9.7
   9.8   9.9  10.   10.1  10.2  10.3  10.4  10.5  10.6  10.7  10.8  10.9
  11.   11.1  11.2  11.3  11.4  11.5  11.6  11.7  11.8  11.9  12.   12.1
  12.2  12.3  12.4  12.5  12.6  12.7  12.8  12.9  13.   13.1  13.2  13.3
  13.4  13.5  13.6  13.7  13.8  13.9  14.   14.1  14.2  14.3  14.4  14.5
  14.6  14.7  14.8  14.9  15.   15.1  15.2  15.3  15.4  15.5  15.6  15.7
  15.8  15.9  16.   16.1  16.2  16.3  16.4  16.5  16.6  16.7  16.8  16.9
  17.   17.1  17.2  17.3  17.4  17.5  17.6  17.7  17.8  17.9  18.   18.1
  18.2  18.3  18.4  18.5  18.6  18.7  18.8  18.9  19.   19.1  19.2  19.3
  19.4  19.5  19.6  19.7  19.8  19.9]


In [74]:
x,y=np.meshgrid(p,p)

In [75]:
print(x)

[[  5.    5.1   5.2 ...,  19.7  19.8  19.9]
 [  5.    5.1   5.2 ...,  19.7  19.8  19.9]
 [  5.    5.1   5.2 ...,  19.7  19.8  19.9]
 ..., 
 [  5.    5.1   5.2 ...,  19.7  19.8  19.9]
 [  5.    5.1   5.2 ...,  19.7  19.8  19.9]
 [  5.    5.1   5.2 ...,  19.7  19.8  19.9]]


In [76]:
print(np.sqrt(x**2 + y**2))  #here we are using x and y as a point we can not do this thing into the normal sqrt function we can evaluate this thing with the help of loop also but we don't want to proivde headache to our mind  

[[  7.07106781   7.14212853   7.21387552 ...,  20.32461562  20.42155724
   20.51852821]
 [  7.14212853   7.21248917   7.28354309 ...,  20.34944717  20.44627105
   20.54312537]
 [  7.21387552   7.28354309   7.35391052 ...,  20.37473926  20.47144353
   20.56817931]
 ..., 
 [ 20.32461562  20.34944717  20.37473926 ...,  27.86000718  27.93080736
   28.00178566]
 [ 20.42155724  20.44627105  20.47144353 ...,  27.93080736  28.00142853
   28.07222827]
 [ 20.51852821  20.54312537  20.56817931 ...,  28.00178566  28.07222827
   28.14284989]]


In [77]:
          ########################Expressing Conditional Logic as Array Operations#########################

In [78]:
x=[1,2,3,4,5,6]
y=[1,2,7,8,9,10]
co=[True,False,True,True,False,False]
result=[(xi if c else yi) for xi,yi,c in zip(x,y,co)]
print(result)

[1, 2, 3, 4, 9, 10]


In [79]:
#we can use the .where function besides this because upper function is taking too much time
result=np.where(co,x,y)
print(result)

[ 1  2  3  4  9 10]


In [80]:
np.where(result>2,3,-4)#if result is greater than 2 then select 3 otherwise select -4

array([-4, -4,  3,  3,  3,  3])

In [81]:
n=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [82]:
np.sum(n)

45

In [83]:
np.sum(n,axis=0)#along the axis 0 row wise

array([12, 15, 18])

In [84]:
np.mean(n)

5.0

In [85]:
np.mean(n,axis=1)

array([ 2.,  5.,  8.])

In [86]:
np.std(n)#standard deviation

2.5819888974716112

In [87]:
np.var(n)#variation

6.666666666666667

In [88]:
np.min(n)

1

In [89]:
np.max(n) #maximum element from the array

9

In [90]:
np.argmin(n) #indicies of minimum element

0

In [91]:
np.argmax(n)#indices of maximum element

8

In [92]:
np.cumsum(n)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [93]:
np.cumprod(n)#commulative product

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [94]:
          ##########################Methods for Boolean Arrays####################

In [95]:
boolean=[True,False,True,False,True]
c=np.array(boolean)

In [96]:
print(np.all(c))

False


In [97]:
print(np.any(c))

True


In [98]:
lst1=[[4,2,2],[5,2,1],[67,23],[1,3,2]]
g=np.array(lst1)
print(np.sort(g))

[[1, 3, 2] [4, 2, 2] [5, 2, 1] [67, 23]]


In [99]:
##################################Unique and Other Set Logic######################
arr3=np.array([1,2,1,2,3,1,3,4,53,1,2,3,4,2,22,2,2])
print(np.unique(arr3))

[ 1  2  3  4 22 53]


In [100]:
#the unique can be implemented as with the pure python
print(sorted(set(arr3)))

[1, 2, 3, 4, 22, 53]


In [102]:
v=np.array([1,2,3,89,0,3,2]) #telling that each value of x contained in the y
print(np.in1d(v,arr3))

[ True  True  True False False  True  True]


In [103]:
print(np.intersect1d(v,arr3))#returns sorted common elements in x as well as in y it is just a copy

[1 2 3]


In [104]:
print(arr3)

[ 1  2  1  2  3  1  3  4 53  1  2  3  4  2 22  2  2]


In [105]:
print(v)

[ 1  2  3 89  0  3  2]


In [107]:
m=np.intersect1d(v,arr3) #it is the shallow copy

In [108]:
print(m)

[1 2 3]


In [109]:
m[0]=5

In [110]:
print(m)

[5 2 3]


In [111]:
print(arr3)

[ 1  2  1  2  3  1  3  4 53  1  2  3  4  2 22  2  2]


In [112]:
print(v)

[ 1  2  3 89  0  3  2]


In [113]:
print(np.setdiff1d(v,arr3)) #set difference

[ 0 89]


In [114]:
print(np.setxor1d(v,arr3)) #symmentric differnce (A-B)U(B-A)

[ 0  4 22 53 89]


In [115]:
            ########################File Input and Output with Arrays#########################

In [116]:
c1=np.arange(10)
print(c1)

[0 1 2 3 4 5 6 7 8 9]


In [117]:
np.save('Some_array',c1)

In [119]:
np.load('Some_array.npy') #this is the file on the disk

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
np.savez('compressed.npz',a=arr3,b=c1) #savez function is compressing the two arrays

In [121]:
f=np.load('compressed.npz') #compressed file we are loading for loading from the disk

In [122]:
f['a'] #if we want access individual file then we can access those as we do in the dictionary

array([ 1,  2,  1,  2,  3,  1,  3,  4, 53,  1,  2,  3,  4,  2, 22,  2,  2])

In [123]:
f['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
print(f) #it will just tell the file type #this is the zip file

In [125]:
np.savez_compressed('compressed_file.npz',a=arr3,b=c1) #compressing our data also

In [126]:
h=np.load('compressed_file.npz')

In [127]:
h['a']

array([ 1,  2,  1,  2,  3,  1,  3,  4, 53,  1,  2,  3,  4,  2, 22,  2,  2])

In [139]:
                ######################Linear Algebra#####################
x=np.array([[1,2],[4,5]])

In [140]:
y=np.array([[12,13,14],[15,16,17]])

In [141]:
print(x.dot(y))

[[ 42  45  48]
 [123 132 141]]


In [142]:
#it is same as to write
np.dot(x,y)

array([[ 42,  45,  48],
       [123, 132, 141]])

In [143]:
x@y #it is also performing matrix multipication

array([[ 42,  45,  48],
       [123, 132, 141]])

In [153]:
np.diag(y)

array([12, 16])

In [154]:
np.dot(x,y)

array([[ 42,  45,  48],
       [123, 132, 141]])

In [155]:
np.trace(x)

6

In [156]:
np.linalg.det(x)

-2.9999999999999996

In [159]:
l=np.linalg.eig(x) #here it will return a tuple of both the arrays or eigen values or eigen vectors

In [160]:
print(l)

(array([-0.46410162,  6.46410162]), array([[-0.80689822, -0.34372377],
       [ 0.59069049, -0.9390708 ]]))


In [162]:
np.linalg.inv(x)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [163]:
np.linalg.pinv(x)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [165]:
np.linalg.qr(x) #produce the qr decomposition of the matrix

(array([[-0.24253563, -0.9701425 ],
        [-0.9701425 ,  0.24253563]]), array([[-4.12310563, -5.33578375],
        [ 0.        , -0.72760688]]))

In [166]:
np.linalg.svd(x) #compute the singular value from the matrix

(array([[-0.32453643, -0.9458732 ],
        [-0.9458732 ,  0.32453643]]),
 array([ 6.76782894,  0.44327362]),
 array([[-0.60699365, -0.79470668],
        [ 0.79470668, -0.60699365]]))

In [171]:
b=np.array([1,2])
np.linalg.solve(x,b) #like AX=B as we do in the matrix like a calculation of the x and y values using the system of equations it is returning the corresponding x and y values when we are using the system of quations

array([-0.33333333,  0.66666667])

In [172]:
np.linalg.lstsq(x,b) #least square solution

(array([-0.33333333,  0.66666667]),
 array([], dtype=float64),
 2,
 array([ 6.76782894,  0.44327362]))

In [173]:
                   ###################Pseudorandom Number Generation####################

In [181]:
print(np.random.seed(123))

None


In [182]:
print(np.random.randn(10))

[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025  1.65143654
 -2.42667924 -0.42891263  1.26593626 -0.8667404 ]


In [183]:
np.random.seed(123)

In [184]:
print(np.random.randn(10))

[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025  1.65143654
 -2.42667924 -0.42891263  1.26593626 -0.8667404 ]


In [185]:
np.random.randn(10) #here value is changed because I have not called the seed function  seed function is fixing the value for that integer part which we are passing as an argument in the random function

array([-0.67888615, -0.09470897,  1.49138963, -0.638902  , -0.44398196,
       -0.43435128,  2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ])

In [188]:
np.random.permutation(10) #because in the permutation there is the selection

array([7, 5, 6, 8, 9, 3, 0, 4, 1, 2])

In [195]:
lst=[1,2,3,4,5]  
np.random.shuffle(lst) #this function does not return anything it just shuffles the original list in random mannner
print(lst)

[1, 3, 2, 5, 4]


In [199]:
np.random.rand(10) #uniform distribution

array([ 0.5491621 ,  0.55671906,  0.00413464,  0.63802252,  0.05764801,
        0.04302691,  0.87505113,  0.2925876 ,  0.76276766,  0.36786526])

In [203]:
np.random.randint(3,10) #generate an random number withing given range

9

In [205]:
np.random.binomial(10,0.5) #the first argument is the number of trials and the second one is the probability and the 3rd one is the size how much time the operation is going to perform

3

In [206]:
np.random.binomial(10,0.5,(1,2,3)) # If size is None (default), a single value is returned if n and p are both scalars. Otherwise, np.broadcast(n, p).size samples are drawn.

array([[[3, 4, 6],
        [7, 5, 7]]])

In [210]:
np.random.uniform() #return the uniform value between the [0,1)

0.17108182920509907

In [211]:
                   #################Random Walks########################

In [215]:
#walk is just the commulative sum of all the random steps#
nsteps=1000
draws=np.random.randint(0,2,size=nsteps)
steps=np.where(draws>0,1,-1) 
walk=np.cumsum(steps)
print(walk)

[ -1  -2  -1   0   1   2   1   2   1   2   3   2   1   2   1   0   1   2
   1   0  -1   0  -1   0   1   2   1   0  -1  -2  -1  -2  -3  -4  -5  -4
  -3  -2  -3  -2  -1   0   1   0   1   2   1   2   3   4   5   4   3   4
   3   2   1   0   1   2   3   2   3   2   3   2   1   2   1   2   3   4
   3   2   1   0   1   0  -1  -2  -1   0  -1  -2  -3  -2  -1  -2  -1   0
   1   0  -1   0   1   0   1   0   1   0   1   0  -1   0  -1   0   1   2
   1   2   1   0  -1  -2  -1  -2  -3  -4  -3  -4  -3  -2  -3  -4  -5  -6
  -5  -6  -5  -4  -3  -2  -1   0  -1  -2  -1  -2  -3  -4  -5  -6  -7  -6
  -5  -6  -5  -4  -5  -6  -5  -4  -5  -4  -3  -2  -1   0  -1  -2  -1  -2
  -3  -4  -5  -6  -7  -6  -5  -4  -3  -4  -3  -4  -5  -4  -5  -6  -5  -6
  -7  -6  -7  -6  -5  -6  -5  -6  -7  -8  -9 -10  -9 -10  -9 -10 -11 -10
 -11 -10 -11 -10 -11 -10 -11 -12 -13 -14 -13 -14 -13 -12 -13 -12 -13 -14
 -13 -12 -11 -12 -11 -10 -11 -12 -11 -12 -11 -10  -9 -10 -11 -12 -11 -10
  -9 -10 -11 -12 -11 -10  -9  -8  -7  -6  -5  -4  -

In [216]:
print(walk.min())

-42


In [217]:
print(walk.max())

5


In [218]:
print(walk.argmax()) #returning the index of the maximum walk

50


In [219]:
(np.abs(walk)>=10).argmax() #that is the index number 191 whwere the walk has reahed greater than 10

191

In [220]:
         ####simulating many random walks we can perform these using the 2d array#######################
#for eg:
msteps=1000
draws1=np.random.randint(0,2,size=(nsteps,msteps))
step=np.where(draws1>0,1,-1) #total 1000000 these much steps are going to be done
walk=step.cumsum(1) # this is along the axis 1 
print(walk) #this is returning the 2d array

[[  1   0  -1 ..., -24 -23 -24]
 [ -1  -2  -3 ...,  -2  -3  -2]
 [  1   0  -1 ...,  -2  -1  -2]
 ..., 
 [ -1   0   1 ...,   0  -1  -2]
 [ -1  -2  -1 ..., -38 -39 -38]
 [ -1   0   1 ...,   2   3   4]]


In [221]:
print(walk.max())

114


In [222]:
print(walk.min())

-122


In [223]:
print(walk.argmin()) #index number

243983


In [224]:
print(walk.argmax()) #index number of the maximum walk

922839
