In [3]:
#we are genearting the random data here in the randn() function first argument is telling the number of array inside the array but 2nd argument is telling the number of elements in the each array
import numpy as np
data = np.random.randn(2,4)
print(data)

[[-0.07778997 -2.27564211 -1.13187698  1.07733204]
 [ 0.26021178  0.36893584 -0.70998592 -0.916342  ]]


In [4]:
#now if we do some calclation on the numpy array then
print(data*10)
#all the elements are multiplyied by 10 in the arrays

[[ -0.7778997  -22.75642105 -11.31876979  10.77332042]
 [  2.60211784   3.68935839  -7.09985925  -9.16341999]]


In [5]:
#what if we do same thing with the lists
lst=[1,2,34,5]
print(lst+lst)
#it is added all the elements in the new list of the lst

[1, 2, 34, 5, 1, 2, 34, 5]


In [6]:
#what if we do smae thing with numpy array??????????
print(data+data)
#it is proving the sum of each element with the each element

[[-0.15557994 -4.55128421 -2.26375396  2.15466408]
 [ 0.52042357  0.73787168 -1.41997185 -1.832684  ]]


In [7]:
#.shape function to provide the tuple which contain the nd array and the number of elemement in the each array
data.shape

(2, 4)

In [8]:
#.dtype function tells the data type of the array
data.dtype

dtype('float64')

In [9]:
            ################creation of the nd-array##################
lst=[1,2,3,4,5]
arr=np.array(lst)
print(arr)

[1 2 3 4 5]


In [10]:
#nested sequence returns the nd array like in below example it is 2d array
lst1=[[1,2,3],[4,5,6]]
arr1=np.array(lst1)
print(arr)

[1 2 3 4 5]


In [11]:
lst1=[[1,2,3,4],[1,2,3],[1,2]]
arr2=np.array(lst1)
print(arr2.shape)
print(arr2.ndim)
#not showing the 2nd element in the output because there is not the symmentry

(3,)
1


In [12]:
#ndim function returns the dimension of the numpy array
ls=[[1,23,3],[2,3,5],[4,5,6]]
arrx=np.array(ls)
print(arrx.ndim)

2


In [13]:
#.zeros() function to create the numpy array
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
#it will create the numpy 3d array with each array containg the 10 zeros basically we are passing the tuple of dimension and elements as in the .shape function
np.zeros((3,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
#it will create the numpy array with all elements have 1
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
np.ones((3,10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [17]:
#it will create the two dimensional array and inside the each array conatins 3d array and each array conatins 2 elements
np.empty((2,3,2))

array([[[  6.93422779e-310,   2.17182088e-316],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   5.40144760e-062]],

       [[  8.98355748e-067,   2.98903387e-032],
        [  8.16322876e-043,   5.88458962e-062],
        [  1.88865512e+185,   6.52285918e-038]]])

In [18]:
#.arange() function like a range function it is 
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.arange(1,15,2) #last argument is for jumps

array([ 1,  3,  5,  7,  9, 11, 13])

In [20]:
arr=np.asarray([1,2,3,3,4,5])
print(arr)

[1 2 3 3 4 5]


In [21]:
arr=np.asarray([1,2,3,7,8])
print(arr)

[1 2 3 7 8]


In [22]:
arr1=np.asarray(arr)
print(arr1)

[1 2 3 7 8]


In [23]:
arr1=np.array(arr)
print(arr1)

[1 2 3 7 8]


In [24]:
#produce a ones array
x=np.ones_like(15)
print(x)

1


In [25]:
z=np.zeros_like(15)
print(z)

0


In [135]:
#full function 2 dimensional array having 3 rows in each array
v=np.full([3,2],68,dtype=int)
print(v)
print(v.ndim)

[[68 68]
 [68 68]
 [68 68]]
2


In [27]:
                  ################Data types for ndarrays#################

In [28]:
x1=np.array([1,2,3],'i1') #i1 is a typecode which standfor int32 we can write np.int8 also there
print(x1)

[1 2 3]


In [29]:
#we are getting 245 in the output because we cant store the negative numbers in the unsigned integers thus it is negate the 11 from the 256-11=245
x2=np.array([-11,2,3],np.uint8)
print(x2)

[245   2   3]


In [30]:
x3=np.array([1,2,3,4],'f')
print(x3)

[ 1.  2.  3.  4.]


In [31]:
x3.dtype

dtype('float32')

In [32]:
x4=np.array('Aman')
print(x4)

Aman


In [33]:
x4.dtype

dtype('<U4')

In [34]:
x5=np.array([1+2j,1+3j])
print(x5)
print(x5.dtype)

[ 1.+2.j  1.+3.j]
complex128


In [35]:
#we are making the object here we can use x6 as object
x6=np.array([(1,2)],'O')
print(x6)
print(x6.dtype)

[[1 2]]
object


In [36]:
x3.astype(np.int64)

array([1, 2, 3, 4])

In [37]:
x7=np.arange(10)
print(x7)
x8=np.array([1.3,2.6,7.8],dtype=x7.dtype)
print(x8)

[0 1 2 3 4 5 6 7 8 9]
[1 2 7]


In [38]:
                       ###########Arithmetics in the numpy#################
#Lets start the Arithmetics in the numpy numpy users call it vectorization (Because we are not using loops here) these operation takes place element wise
#we have to use equal arguments because the operation is taking place in the pairs 
arrr1=np.array([1,2,3,4])
arrr2=np.array([5,6,7,8])
print(arrr1*arrr2)

[ 5 12 21 32]


In [39]:
print(arrr1-arrr2)

[-4 -4 -4 -4]


In [40]:
print(arrr1+arrr2)

[ 6  8 10 12]


In [41]:
print(arrr2/arrr1)

[ 5.          3.          2.33333333  2.        ]


In [42]:
print(1/arrr1)

[ 1.          0.5         0.33333333  0.25      ]


In [43]:
print(arrr1**2)

[ 1  4  9 16]


In [44]:
print(arrr2>arrr1)#it is comparing each element

[ True  True  True  True]


In [45]:
               ##################3#Basic indexing and slicing in the numpy#########################
arr6=np.array([1,2,5,2,4,6,8,9,10,11])
print(arr6)

[ 1  2  5  2  4  6  8  9 10 11]


In [46]:
arr6[6] #we can fetch the perticular element from the array through it  

8

In [48]:
arr_slice=arr6[5:8]
print(arr_slice)

[6 8 9]


In [50]:
arr_slice[0]=78
print(arr_slice) #these changes will reflect into the original array also

[78  8  9]


In [51]:
print(arr6)

[ 1  2  5  2  4 78  8  9 10 11]


In [52]:
#we can use the the bare slicing  to change the all values in the sliced array
arr_slice[:]=90
print(arr_slice)

[90 90 90]


In [53]:
print(arr6)

[ 1  2  5  2  4 90 90 90 10 11]


In [54]:
#Now if we do not want to change the original sequence then
x=arr6[5:8].copy() # we can use this it is basically our shallow copy
print(x)

[90 90 90]


In [55]:
x[1]=0

In [56]:
print(x)
print(arr6) #original sequence will not change

[90  0 90]
[ 1  2  5  2  4 90 90 90 10 11]


In [57]:
#for 2d array we can do it like this
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])#it conatins three rows and three columns
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
#how we can fetch the data at the specific point
print(arr4[1])

[4 5 6]


In [59]:
print(arr4[1][1])

5


In [61]:
#another style to detch the element mention the row number and column number to fetch it
print(arr4[1,1])

5


In [63]:
#with 3d array
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [68]:
arr3d[0][1][2]

6

In [69]:
#simplified version
arr3d[0,1,2]

6

In [72]:
arr3d1=np.array([[1,2,3],[[4,5,6],[7,8,9]]])
print(arr3d1)

[[1, 2, 3] [[4, 5, 6], [7, 8, 9]]]


In [75]:
arr3d1[1][0][2]

6

In [76]:
                ################Indexes with slices in ndarray##################
arr4[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [77]:
arr4[1:,1:]##slicing the elements in the 2d array first slice is for columns and second  is for elements inside it

array([[5, 6],
       [8, 9]])

In [80]:
arr4[:2,1:] #selecting the rows form 0 to 1 and elements inside it from 1 to 2 this is the slicing here

array([[2, 3],
       [5, 6],
       [8, 9]])

In [81]:
arr4[1,:2] #selected first row and last two elements from it

array([4, 5])

In [82]:
arr4[1:,2]

array([6, 9])

In [83]:
arr4[1:,2]=1.2
print(arr4)#conatins the same data type all over the region

[[1 2 3]
 [4 5 1]
 [7 8 1]]


In [85]:
               ######################Functions in the numpy###########################
z=np.array([1,2,3,4,59,10])
m=np.sqrt(z)
print(m)

[ 1.          1.41421356  1.73205081  2.          7.68114575  3.16227766]


In [86]:
j=np.exp(z)
print(j)

[  2.71828183e+00   7.38905610e+00   2.00855369e+01   5.45981500e+01
   4.20121040e+25   2.20264658e+04]


In [87]:
#providing the absolute value of each element
print(np.abs(z))

[ 1  2  3  4 59 10]


In [88]:
#provding the square of the each element
print(np.square(z))

[   1    4    9   16 3481  100]


In [89]:
print(np.log(z))

[ 0.          0.69314718  1.09861229  1.38629436  4.07753744  2.30258509]


In [90]:
print(np.log10(z))

[ 0.          0.30103     0.47712125  0.60205999  1.77085201  1.        ]


In [91]:
print(np.log2(z))

[ 0.          1.          1.5849625   2.          5.88264305  3.32192809]


In [93]:
print(np.log1p(z))

[ 0.69314718  1.09861229  1.38629436  1.60943791  4.09434456  2.39789527]


In [95]:
#1 is representing +ve sign -1 is representing negative sign
b=[-1,-2,3,4,5]
print(np.sign(b))

[-1 -1  1  1  1]


In [96]:
n=[-1.2,-2.2,3.1,4.4,5.5]
print(np.ceil(n))

[-1. -2.  4.  5.  6.]


In [97]:
print(np.floor(n))

[-2. -3.  3.  4.  5.]


In [99]:
#round elements to the nearest integer
print(np.rint(n))
print(n)

[-1. -2.  3.  4.  6.]
[-1.2, -2.2, 3.1, 4.4, 5.5]


In [101]:
c,k=np.modf(n)
print(c)
print(k)

[-0.2 -0.2  0.1  0.4  0.5]
[-1. -2.  3.  4.  5.]


In [106]:
j=np.array([1,2,3])
print(np.isnan(j))

[False False False]


In [107]:
#check the elements they are finite or infinite
print(np.isfinite(n))

[ True  True  True  True  True]


In [108]:
#returning cosine value
print(np.cos(z))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362 -0.77108022 -0.83907153]


In [109]:
#returning hyperbolic values
print(np.cosh(z))

[  1.54308063e+00   3.76219569e+00   1.00676620e+01   2.73082328e+01
   2.10060520e+25   1.10132329e+04]


In [111]:
f = np.array([-1,1])
print(np.arccos(f))

[ 3.14159265  0.        ]


In [112]:
print(np.logical_not(z))

[False False False False False False]


In [114]:
lq=np.array([1.2,3.4,5.0,6.0,7.0])
pq=np.array([2.2,6.7,8.8,9.9,7.5])
print(np.add(lq,pq))

[  3.4  10.1  13.8  15.9  14.5]


In [115]:
print(np.subtract(lq,pq))

[-1.  -3.3 -3.8 -3.9 -0.5]


In [117]:
print(np.multiply(lq,pq))

[  2.64  22.78  44.    59.4   52.5 ]


In [118]:
#provide the actual value
print(np.divide(lq,pq))

[ 0.54545455  0.50746269  0.56818182  0.60606061  0.93333333]


In [119]:
#provides the floor value
print(np.floor_divide(lq,pq))

[ 0.  0.  0.  0.  0.]


In [120]:
print(np.power(lq,pq))

[  1.49347770e+00   3.63838577e+03   1.41558528e+06   5.05472321e+07
   2.17888997e+06]


In [122]:
lq=np.array([1.2,3.4,5.0,6.0,7.8])
print(np.maximum(lq,pq))

[ 2.2  6.7  8.8  9.9  7.8]


In [123]:
#ignores the NAN (Not a Number)
print(np.fmax(lq,pq))

[ 2.2  6.7  8.8  9.9  7.8]


In [124]:
print(np.minimum(lq,pq))

[ 1.2  3.4  5.   6.   7.5]


In [125]:
#providing the sign of other array to the another array
lqw=np.array([1,2,3,4,5])
lqe=np.array([-1,-3,-4,-9,-8])
print(np.copysign(lqw,lqe))

[-1. -2. -3. -4. -5.]


In [126]:
print(np.mod(lqw,lqe))

[ 0 -1 -1 -5 -3]


In [127]:
print(np.greater(lqw,lqe))

[ True  True  True  True  True]


In [129]:
print(np.greater_equal(lq,pq))

[False False False False  True]


In [130]:
print(np.equal(lq,pq))

[False False False False False]


In [131]:
print(np.not_equal(lq,pq))

[ True  True  True  True  True]


In [132]:
print(np.logical_or(lq,pq))

[ True  True  True  True  True]


In [133]:
print(np.logical_and(lq,pq))

[ True  True  True  True  True]


In [134]:
#logical xor  1 1 = 0 , 0 1 =1, 1 0 = 1, 0 0=1   
print(np.logical_xor(lq,pq))

[False False False False False]
