In [1]:
import pandas as pd

In [2]:
ls=[1,2,3,4,'Aman','Agarwal']
#series function
x1=pd.Series(ls)
print(x1)

0          1
1          2
2          3
3          4
4       Aman
5    Agarwal
dtype: object


In [3]:
x1.values #will display the values

array([1, 2, 3, 4, 'Aman', 'Agarwal'], dtype=object)

In [4]:
x1.index #will display the index values as a range function

RangeIndex(start=0, stop=6, step=1)

In [5]:
obj2=pd.Series(ls,index=['a','b','c','d','e','f']) #index should be same in numebr as the values
print(obj2)

a          1
b          2
c          3
d          4
e       Aman
f    Agarwal
dtype: object


In [6]:
obj2.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [7]:
#we can fetch the particular value by using the index as we do in the key value pair
obj2['a']

1

In [8]:
'a' in obj2 #it will return true if the index exist

True

In [9]:

1 in obj2.values #Now it will return true because 1 exists in the values of the obj2

True

In [10]:
obj2['a']=123 #changing the particular value at the particular index 
print(obj2)

a        123
b          2
c          3
d          4
e       Aman
f    Agarwal
dtype: object


In [11]:
obj2*2 #it will double the each value

a               246
b                 4
c                 6
d                 8
e          AmanAman
f    AgarwalAgarwal
dtype: object

In [12]:
print(obj2)

a        123
b          2
c          3
d          4
e       Aman
f    Agarwal
dtype: object


In [13]:
import numpy as np
np.exp(obj2) #it iwll not work because there are some string values also

AttributeError: 'int' object has no attribute 'exp'

In [ ]:

x2=pd.Series([1,2,3,4])
print(x2)

In [14]:
np.exp(x2) #now this function will work

NameError: name 'x2' is not defined

In [15]:
#we can also define the dataset by using the dictionary

In [16]:
dict={'1':2,'2':3,'8':10}


In [17]:
pd.Series(dict)

1     2
2     3
8    10
dtype: int64

In [18]:

states=['A','B','C','D','1','2'] #this thing is basically matching the dictionary with provided indecises
obj9=pd.Series(dict,index=states)
print(obj9)

A    NaN
B    NaN
C    NaN
D    NaN
1    2.0
2    3.0
dtype: float64


In [19]:
#isnull function returns true when object value is null
pd.isnull(obj9)

A     True
B     True
C     True
D     True
1    False
2    False
dtype: bool

In [20]:
#basically NaN stands for the not a number #Not null is just the reverse of the isnull function
pd.notnull(obj9)

A    False
B    False
C    False
D    False
1     True
2     True
dtype: bool

In [21]:
obj9.isnull()

A     True
B     True
C     True
D     True
1    False
2    False
dtype: bool

In [22]:
print(obj2)
print(obj9)

a        123
b          2
c          3
d          4
e       Aman
f    Agarwal
dtype: object
A    NaN
B    NaN
C    NaN
D    NaN
1    2.0
2    3.0
dtype: float64


In [23]:
obj2+obj9 #it basically returns those indexes with the value those have both the index commmon and having the same data otherwise it will return the NaN which means not a number

1    NaN
2    NaN
A    NaN
B    NaN
C    NaN
D    NaN
a    NaN
b    NaN
c    NaN
d    NaN
e    NaN
f    NaN
dtype: object

In [24]:
ob1 = pd.Series([1,2,3,4,5,6],index=['A','B','C','D','E','F'])
print(ob1)

A    1
B    2
C    3
D    4
E    5
F    6
dtype: int64


In [25]:
ob2=pd.Series([1,2,3,4,5,6],index= ['A','C','D','B','E','F'])
print(ob2)

A    1
C    2
D    3
B    4
E    5
F    6
dtype: int64


In [26]:
ob2+ob1 # adding the values with their corresponding index

A     2
B     6
C     5
D     7
E    10
F    12
dtype: int64

In [27]:
#we can assign the name also to the object

In [28]:
ob1.index.name='Aman'
ob1.name='Agarwal'

In [29]:
print(ob1)

Aman
A    1
B    2
C    3
D    4
E    5
F    6
Name: Agarwal, dtype: int64


In [30]:
#A series index can be altered by the assigning index
ob1.index=['x','y','z','A','B','C']

In [31]:
print(ob1)

x    1
y    2
z    3
A    4
B    5
C    6
Name: Agarwal, dtype: int64


In [32]:
#################Dataframe################ #ALways provide the list #1,2,3,4,5 are the name of the columns
random_data={'1':['Aman','x'],'2':['Agarwal','y'],'3':['abhishek','z'],'4':['Prajapati','a'],'5':['Ankit','b']}
frame=pd.DataFrame(random_data)
print(frame)

      1        2         3          4      5
0  Aman  Agarwal  abhishek  Prajapati  Ankit
1     x        y         z          a      b


In [33]:
frame.head() #it is going to provide the starting 5 rows to us

1        2         3          4      5
0  Aman  Agarwal  abhishek  Prajapati  Ankit
1     x        y         z          a      b

In [34]:
frame.columns

Index(['1', '2', '3', '4', '5'], dtype='object')

In [35]:
frame.index

RangeIndex(start=0, stop=2, step=1)

In [36]:
data={'1':['a','b','c'],'2':['x','y','z'],'3':['A','B','C']}

In [37]:
frame=pd.DataFrame(data)
print(frame)

   1  2  3
0  a  x  A
1  b  y  B
2  c  z  C


In [38]:
y=pd.DataFrame(data,columns=['L','M','N']) #it is showing the Empty dataframe because I ahve selected those column which does not exist in the DataFrame
pd.DataFrame(data,columns=['2','3','1'])

2  3  1
0  x  A  a
1  y  B  b
2  z  C  c

In [39]:
z=pd.DataFrame(data,columns=['2','3','1','4'],index=['one','two','three']) #we can update the naem of the indexes
#Ihave passed the column as '4' which does not exists in the DataFrame then it wil show as the NaN which means not a number
print(z)

       2  3  1    4
one    x  A  a  NaN
two    y  B  b  NaN
three  z  C  c  NaN


In [40]:
z['4']=13 #now I ahve assigned the 13 to the column no.4

In [41]:
print(z)

       2  3  1   4
one    x  A  a  13
two    y  B  b  13
three  z  C  c  13


In [42]:
z.index


Index(['one', 'two', 'three'], dtype='object')

In [43]:
z.columns

Index(['2', '3', '1', '4'], dtype='object')

In [44]:
z['2'] #this will work for all the columns name but . will work only for those only if the attribute exists in teh dataframe

one      x
two      y
three    z
Name: 2, dtype: object

In [45]:
#we can also retreive the rows by using the loc function
z.loc['one']

2     x
3     A
1     a
4    13
Name: one, dtype: object

In [46]:
#by using iloc we can pass the indexing as we do in the array
z.iloc[0]

2     x
3     A
1     a
4    13
Name: one, dtype: object

In [47]:
z['4']=np.arange(3)

In [48]:
print(z)

       2  3  1  4
one    x  A  a  0
two    y  B  b  1
three  z  C  c  2


In [49]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])
z['4']=val
print(z)

       2  3  1    4
one    x  A  a  NaN
two    y  B  b -1.2
three  z  C  c  NaN


In [50]:
#by using del we can delete a particular column
del z['4']

In [51]:
print(z
     )

       2  3  1
one    x  A  a
two    y  B  b
three  z  C  c


In [52]:
z.columns

Index(['2', '3', '1'], dtype='object')

In [53]:
z['x']=z['2']=='x'

In [54]:
print(z
     )

       2  3  1      x
one    x  A  a   True
two    y  B  b  False
three  z  C  c  False


In [55]:
#by using the nested dictionaries where outer columns are as the columns and the inner ones are rows
pop={'Aman':{2001:2.4,2002:2.9},'Agarwal':{2000:1.5,2001:1.7,2002:3.6}}

In [56]:
fm=pd.DataFrame(pop)

In [57]:
print(fm)

      Aman  Agarwal
2000   NaN      1.5
2001   2.4      1.7
2002   2.9      3.6


In [58]:
fm.T #it is basically transposing the given dataframe


2000  2001  2002
Aman      NaN   2.4   2.9
Agarwal   1.5   1.7   3.6

In [59]:
fm.index.name='Aman'
fm.columns.name='Agarwal'

In [60]:
print(fm
     )

Agarwal  Aman  Agarwal
Aman                  
2000      NaN      1.5
2001      2.4      1.7
2002      2.9      3.6


In [61]:
fm.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [63]:
#pandas index objects are responsible to holding the axis labels
obj=pd.Series(range(3),index=['a','b','c'])
print(obj)

a    0
b    1
c    2
dtype: int64


In [64]:
index=obj.index

In [65]:
print(index)

Index(['a', 'b', 'c'], dtype='object')


In [82]:
index['1']='d' #it is providing the error because index objects are not mutable

TypeError: Index does not support mutable operations

In [79]:
labels=pd.Index(np.arange(3)) #here we are making the labels as teh index object
print(labels)

Int64Index([0, 1, 2], dtype='int64')


In [80]:
obj2=pd.Series([1.5,2,0],index=labels)
print(obj2)

0    1.5
1    2.0
2    0.0
dtype: float64


In [81]:
labels is obj2.index 

True

In [85]:
1.5 in obj2.values

True

In [87]:
#selection with duplicate index will select all the dublicate index because we are treating them as the individual column name
dub_labels=pd.Index(['1','1','2','2'])
print(dub_labels)

Index(['1', '1', '2', '2'], dtype='object')


In [88]:
##Reindexing

In [89]:
obj10=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
print(obj10)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64


In [92]:
obj10=obj10.reindex(['a','b','c','d'])
print(obj10)

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64


In [98]:
obj2=obj10.reindex(['a','b','c','d','e']) #it will create the new object with the same index value and values are corresponding to those are of the obj10

In [99]:
print(obj2)

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64


In [104]:
objx=pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [105]:
print(objx)

0      blue
2    purple
4    yellow
dtype: object


In [106]:
objx.reindex(range(1,6),method='ffill') #it is filling according to the previous index

1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [112]:
frame2=objx.reindex([1,2,3,4,7])

In [113]:
print(frame2)

1       NaN
2    purple
3       NaN
4    yellow
7       NaN
dtype: object


In [116]:
stat=['A']
frame2.loc[[1,2,3,4]]

1       NaN
2    purple
3       NaN
4    yellow
dtype: object

In [117]:
frame2.iloc[[0,1,2]]

1       NaN
2    purple
3       NaN
dtype: object

In [118]:
#dropping the entries from the axis
obj7=pd.Series(np.arange(5),index=['a','b','c','d','e'])
print(obj7)

a    0
b    1
c    2
d    3
e    4
dtype: int64


In [121]:
obj7.drop('a') #it is just a copy but the actual obj7 has not modified 

b    1
c    2
d    3
e    4
dtype: int64

In [122]:
print(obj7)

a    0
b    1
c    2
d    3
e    4
dtype: int64


In [123]:
obj7.drop(['a','b'])

c    2
d    3
e    4
dtype: int64

In [124]:
data=pd.DataFrame(np.arange(16).reshape(4,4),index=[1,2,3,4],columns=['A','B','C','D'])

In [125]:
print(data)

    A   B   C   D
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15


In [126]:
data.drop('A',axis=1)

B   C   D
1   1   2   3
2   5   6   7
3   9  10  11
4  13  14  15

In [128]:
data.drop(1) #it is just dropping the column 1 it is actually showing that it is dropping the column but in actually it is not dropping

A   B   C   D
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15

In [129]:
#by using inplace function we can modify the original once
data.drop('A',axis=1,inplace=True)

In [130]:
print(data)

    B   C   D
1   1   2   3
2   5   6   7
3   9  10  11
4  13  14  15


In [136]:
data[2:]

B   C   D
3   9  10  11
4  13  14  15

In [137]:
data[:2]

B  C  D
1  1  2  3
2  5  6  7

In [138]:
data[2:4]

B   C   D
3   9  10  11
4  13  14  15

In [143]:
data[1:2]

B  C  D
2  5  6  7

In [147]:
data[['C','B']]

C   B
1   2   1
2   6   5
3  10   9
4  14  13

In [148]:
data[data['B']>5]

B   C   D
3   9  10  11
4  13  14  15

In [149]:
data<5  #boolean data frame

B      C      D
1   True   True   True
2  False  False  False
3  False  False  False
4  False  False  False

In [150]:
data[data<5] #it wiill check this for all the indexes

B    C    D
1  1.0  2.0  3.0
2  NaN  NaN  NaN
3  NaN  NaN  NaN
4  NaN  NaN  NaN

In [151]:
data[data<5]=0
print(data)

    B   C   D
1   0   0   0
2   5   6   7
3   9  10  11
4  13  14  15


In [153]:
data.loc[3,['B','C']]

B     9
C    10
Name: 3, dtype: int64

In [158]:
data.iloc[2,[0,2]]

B     9
D    11
Name: 3, dtype: int64

In [159]:
data.iloc[2]

B     9
C    10
D    11
Name: 3, dtype: int64

In [160]:
data.iloc[[1,2],[0,1,2]]

B   C   D
2  5   6   7
3  9  10  11

In [161]:
ser=pd.Series(np.arange(3))

In [162]:
print(ser)

0    0
1    1
2    2
dtype: int64


In [165]:
ser.iloc[-1] #from the bottom

2

In [166]:
#loc is for the labels iloc is for the integers

In [167]:
#############Arithmetic and Data Allignment
s1=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])
s2=pd.Series([1,2,3],index=['a','e','g'])

In [168]:
s1+s2 #here only a and e data will be added because these indexes are common in both the dataframes

a    2.0
b    NaN
c    NaN
d    NaN
e    7.0
f    NaN
g    NaN
dtype: float64

In [186]:
df1=pd.DataFrame(np.arange(16).reshape((4,4)),columns=['a','b','c','d'],index=list('1234'))

In [187]:
print(df1)

    a   b   c   d
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15


In [189]:
df2=pd.DataFrame(np.arange(9).reshape((3,3)),columns=['a','b','d'],index=list('123'))

In [190]:
print(df2)

   a  b  d
1  0  1  2
2  3  4  5
3  6  7  8


In [191]:
df1+df2

a     b   c     d
1   0.0   2.0 NaN   5.0
2   7.0   9.0 NaN  12.0
3  14.0  16.0 NaN  19.0
4   NaN   NaN NaN   NaN

In [197]:
df3=pd.DataFrame({'A':[1,2]})

In [198]:
print(df3)

   A
0  1
1  2


In [199]:
df4=pd.DataFrame({'B':[3,4]})

In [200]:
print(df4)

   B
0  3
1  4


In [201]:
df3-df4

A   B
0 NaN NaN
1 NaN NaN

In [202]:
df5=pd.DataFrame({'A':[3,4]})

In [203]:
print(df5)

   A
0  3
1  4


In [205]:
df3-df5 #subtraction operation on the dataframe

A
0 -2
1 -2

In [206]:
df1.add(df2,fill_value=0) #At the place of NaN value the fill value is the 0 thats why we use the fill_value function

a     b     c     d
1   0.0   2.0   2.0   5.0
2   7.0   9.0   6.0  12.0
3  14.0  16.0  10.0  19.0
4  12.0  13.0  14.0  15.0

In [207]:
1/df1

a         b         c         d
1       inf  1.000000  0.500000  0.333333
2  0.250000  0.200000  0.166667  0.142857
3  0.125000  0.111111  0.100000  0.090909
4  0.083333  0.076923  0.071429  0.066667

In [208]:
###using rdiv function
df1.rdiv(1)

a         b         c         d
1       inf  1.000000  0.500000  0.333333
2  0.250000  0.200000  0.166667  0.142857
3  0.125000  0.111111  0.100000  0.090909
4  0.083333  0.076923  0.071429  0.066667

In [210]:
df1.rdiv(2) #2/df1

a         b         c         d
1       inf  2.000000  1.000000  0.666667
2  0.500000  0.400000  0.333333  0.285714
3  0.250000  0.222222  0.200000  0.181818
4  0.166667  0.153846  0.142857  0.133333

In [226]:
df2.floordiv(df1,fill_value=0)   #because fill_value is 0 then there will be the operation 0//df2

a    b    c    d
1  NaN  1.0 -0.0  0.0
2  0.0  0.0 -0.0  0.0
3  0.0  0.0 -0.0  0.0
4 -0.0 -0.0 -0.0 -0.0

In [225]:
df1//df2 

a    b   c    d
1  NaN  1.0 NaN  1.0
2  1.0  1.0 NaN  1.0
3  1.0  1.0 NaN  1.0
4  NaN  NaN NaN  NaN

In [228]:
df1.radd(df2,fill_value=97) #radd has the counter part

a      b      c      d
1    0.0    2.0   99.0    5.0
2    7.0    9.0  103.0   12.0
3   14.0   16.0  107.0   19.0
4  109.0  110.0  111.0  112.0

In [229]:
1-df1 #here 1 is written 1st then we have written df1

a   b   c   d
1   1   0  -1  -2
2  -3  -4  -5  -6
3  -7  -8  -9 -10
4 -11 -12 -13 -14

In [230]:
df1.rsub(1) #here df1 is written 1st then we have written 1

a   b   c   d
1   1   0  -1  -2
2  -3  -4  -5  -6
3  -7  -8  -9 -10
4 -11 -12 -13 -14

In [231]:
df1/df2

a         b   c      d
1       NaN  1.000000 NaN  1.500
2  1.333333  1.250000 NaN  1.400
3  1.333333  1.285714 NaN  1.375
4       NaN       NaN NaN    NaN

In [233]:
df1.div(df2)   #now if we write the rdiv and we want to have the same result then we have to write a df2.rdiv(df1)

a         b   c      d
1       NaN  1.000000 NaN  1.500
2  1.333333  1.250000 NaN  1.400
3  1.333333  1.285714 NaN  1.375
4       NaN       NaN NaN    NaN

In [234]:
arr=np.arange(12).reshape((3,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [235]:
arr-arr[0]   #subtracting the whole row value vise aur we can say element wise

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [237]:
frame3=pd.DataFrame(np.arange(12).reshape(3,4),columns=['A','B','C','D'],index=['Aman','Agarwal','Anit'])

In [238]:
print(frame3)

         A  B   C   D
Aman     0  1   2   3
Agarwal  4  5   6   7
Anit     8  9  10  11


In [239]:
series=frame3.iloc[0]

In [240]:
print(series
     )

A    0
B    1
C    2
D    3
Name: Aman, dtype: int64


In [241]:
frame3-series

A  B  C  D
Aman     0  0  0  0
Agarwal  4  4  4  4
Anit     8  8  8  8

In [242]:
frame3+series

A   B   C   D
Aman     0   2   4   6
Agarwal  4   6   8  10
Anit     8  10  12  14

In [243]:
series2=pd.Series(range(3),index=['Aman','B','C'])

In [244]:
print(series2)

Aman    0
B       1
C       2
dtype: int64


In [245]:
frame3 + series2

A  Aman     B     C   D
Aman    NaN   NaN   2.0   4.0 NaN
Agarwal NaN   NaN   6.0   8.0 NaN
Anit    NaN   NaN  10.0  12.0 NaN